### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by danya201272** [RogerFK/pro079#3]
And when press ` i see dont .079 gen (1-6) in console

**Comment by RogerFK** [comment]
You're completely right, everything works but it doesn't show up. I completely missed it, will get fixed in the next patch, thanks for reporting it!

**Comment by RogerFK** [comment]
Fixed --> https://github.com/RogerFK/pro079/commit/ace3747ff56709691b0493437d7ddc0413d288a4
